framework:
    #csrf_protection: true
    fragments: { path: /_fragment }
    #http_method_override: true
    secret: '%env(APP_SECRET)%'

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    php_errors:
        log: true

    templating:
        engines: ['twig', 'php']
        hinclude_default_template: ':default:hinclude.html.twig'

    error_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
