twig:
    default_path: '%kernel.project_dir%/templates'
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

    base_template_class: Sonata\CacheBundle\Twig\TwigTemplate14

    form_themes:
        - 'SonataFormatterBundle:Form:formatter.html.twig'
        - 'SonataMediaBundle:Form:media_widgets.html.twig'
        - 'SonataCoreBundle:Form:datepicker.html.twig'
        - 'SonataCoreBundle:Form:datepicker.html.twig'
        - 'bootstrap_4_horizontal_layout.html.twig'

    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'