fos_comment:
    db_driver: orm
    class:
        model:
            comment: AppBundle\Entity\Comment\Comment
            thread:   AppBundle\Entity\Comment\Thread
    form:
        comment:
            type: sonata_comment_comment
