imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar:             true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.name%_%kernel.environment%.log
            level: debug
#        firephp:
#            type:  firephp
#            level: info

sonata_payment:
    services:
        debug:
            name:    Debug Payment
            enabled: true
            code:    debug
            browser: sonata.payment.browser.curl

            transformers:
                basket: sonata.payment.transformer.basket
                order:  sonata.payment.transformer.order

            options:
                url_callback:  sonata_payment_callback
                url_return_ko: sonata_payment_error
                url_return_ok: sonata_payment_confirmation
