NelmioApiDocBundle:
    resource:     "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:       /doc

sonata_api_news:
    type:         rest
    prefix:       /news
    resource:     "@SonataNewsBundle/Resources/config/routing/api.xml"

sonata_api_media:
    type:         rest
    prefix:       /media
    resource:     "@SonataMediaBundle/Resources/config/routing/api.xml"

sonata_api_notification:
    type:         rest
    prefix:       /notification
    resource:     "@SonataNotificationBundle/Resources/config/routing/api.xml"