sonata_notification:
    backend: sonata.notification.backend.runtime
#    backend: sonata.notification.backend.doctrine
#    backend: sonata.notification.backend.rabbitmq

    backends:
        rabbitmq:
            exchange: router
            queue:    msgs
            connection:
                host:     localhost
                user:     guest
                pass:     guest
                port:     5672
                vhost:    /

        doctrine:
            max_age:      86400     # max age in second
            pause:        500000    # delay in microseconds
            states:                 # raising errors level
                in_progress: 10
                error:       20
                open:        100
                done:        10000

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataNotificationBundle: ~
