#
# more information can be found here https://sonata-project.org/bundles/comment
#
sonata_comment:
    manager_type: orm # can be 'orm' or 'mongodb'
    class:
        comment:  AppBundle\Entity\Comment # This is an optional value
        thread:   AppBundle\Entity\Thread   # This is an optional value
        category: AppBundle\Entity\Category   # This is an optional value