# Enable Doctrine to map the provided entities
sonata_customer:
    class:
        customer: AppBundle\Entity\Commerce\Customer
        address:  AppBundle\Entity\Commerce\Address
        order:    AppBundle\Entity\Commerce\Order
        user:     AppBundle\Entity\User\User

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataCustomerBundle: ~
