sonata_page:
    ignore_route_patterns:
        - ^sonata_api(.*)          # ignore API routes
        - ^nelmio(.*)       # ignore API doc routes


nelmio_api_doc: ~

fos_rest:
    param_fetcher_listener: true
    body_listener:          true
    format_listener:        true
    view:
        view_response_listener: force
    body_converter:
        enabled: true
        validate: true

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }
    request: { converters:  true }

twig:
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

bazinga_hateoas:
    metadata:
        cache:                file
        file_cache:
            dir:              %kernel.cache_dir%/hateoas