NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

#sonata_api_news:
#    type:         rest
#    prefix:       /api/news
#    resource:     "@SonataNewsBundle/Resources/config/routing/api.xml"
